version: "3"

services:

  mariadb:
    network_mode: traefik_default

  php:
    network_mode: traefik_default
    environment:
      PHP_XDEBUG: 1
      PHP_XDEBUG_REMOTE_AUTOSTART: 1
      PHP_XDEBUG_DEFAULT_ENABLE: 1
      PHP_XDEBUG_REMOTE_CONNECT_BACK: 0
      PHP_IDE_CONFIG: serverName=my-ide
      #  Please see DOCKER_HOST -> https://github.com/docker/for-linux/issues/264
      PHP_XDEBUG_REMOTE_HOST: $DOCKER_PROJECT_HOST
      PHP_MAX_EXECUTION_TIME: ${PHP_MAX_EXECUTION_TIME:-120}
      PHP_POST_MAX_SIZE: ${PHP_POST_MAX_SIZE:-32M}
      PHP_MEMORY_LIMIT: ${PHP_MEMORY_LIMIT:-512M}
      PHP_UPLOAD_MAX_FILESIZE= ${PHP_UPLOAD_MAX_FILESIZE:-32M}
      SSH_AUTH_SOCK: /ssh-agent
    volumes:
      - $SSH_CREDENTIALS:/ssh-agent

  apache:
    network_mode: traefik_default
    environment:
      # For xdebug when we hold a breakpoint we need the server
      # wait until we release the request. APACHE_FCGI_PROXY_TIMEOUT
      # prevent the "Gateway Timeout"
      APACHE_FCGI_PROXY_TIMEOUT: 600
      # Our traefik needs the exact name instead just "php" since
      # it holds many containters and each one has it own unique name.
      APACHE_BACKEND_HOST: "${PROJECT_NAME}_php"
      APACHE_DOCUMENT_ROOT: /var/www/html/web/$PROJECT_BASE_PATH
    labels:

      # Our traefik needs the exact name instead just "apache" since
      # it holds many containters and each one has it own unique name.
      - 'traefik.backend=${PROJECT_NAME}_apache'

      # Minimal modifications to allow subdomain wildcard. Any URL that does not match with
      # taken domains liske pma."project".localhost will fall intro apache container.
      - 'traefik.frontend.rule=HostRegexp:${PROJECT_BASE_URL}, {subdomain:[^.]+}.${PROJECT_BASE_URL}'

  pma:
    network_mode: traefik_default
    environment:
      PMA_USER: root
      PMA_PASSWORD: $DB_ROOT_PASSWORD
      # Our traefik needs the exact name instead just "mariadb" since
      # it holds many containters and each one has it own unique name.
      PMA_HOST: "${PROJECT_NAME}_$DB_HOST"
    labels:
      - 'traefik.frontend.rule=Host:${PROJECT_NAME}.pma.localhost'
      - 'traefik.backend=${PROJECT_NAME}_pma'

  mailhog:
    network_mode: traefik_default
    labels:
      - 'traefik.frontend.rule=Host:${PROJECT_NAME}.mailhog.localhost'
      - 'traefik.backend=${PROJECT_NAME}_mailhog'

  frontend:
    container_name: ${PROJECT_NAME}_frontend
    image: frontid/docker-front-tools:latest
    network_mode: traefik_default
    volumes:
      - ./:/var/www/html
    command: tail -f /dev/null

#  postgres:
#    container_name: ${PROJECT_NAME}_postgres
#    image: wodby/postgres:${POSTGRESS_TAG}
#    network_mode: traefik_default
#    stop_grace_period: 30s
#    environment:
#      POSTGRES_PASSWORD: password
#      POSTGRES_DB: db
#      POSTGRES_USER: db
#    volumes:
#      - ./:/var/www/html

#  postgis:
#    container_name: ${PROJECT_NAME}_postgis
#    network_mode: traefik_default
#    image: mdillon/postgis
#    environment:
#      POSTGRES_PASSWORD: db
#      POSTGRES_USER: db
#      POSTGRES_DB: db
#      PGDATA: /var/lib/postgresql/data/pgdata
#    volumes:
#      - ./:/var/www/html