version: "2"

services:

  mariadb:
    network_mode: traefik_network

  php:
    network_mode: traefik_network
    environment:
      SSH_AUTH_SOCK: /ssh-agent
    volumes:
      - $SSH_CREDENTIALS:/ssh-agent

  apache:
    network_mode: traefik_network
    environment:
      # For xdebug when we hold a breakpoint we need the server
      # wait until we release the request. APACHE_FCGI_PROXY_TIMEOUT
      # prevent the "Gateway Timeout"
      APACHE_FCGI_PROXY_TIMEOUT: 600
      # Our traefik needs the exact name instead just "php" since
      # it holds many containters and each one has it own unique name.
      APACHE_BACKEND_HOST: "${PROJECT_NAME}_php"
    labels:

      # Our traefik needs the exact name instead just "apache" since
      # it holds many containters and each one has it own unique name.
      - 'traefik.backend=${PROJECT_NAME}_apache'

      # Minimal modifications to allow subdomain wildcard. Any URL that does not match with
      # taken domains liske pma."project".localhost will fall intro apache container.
      - 'traefik.frontend.rule=HostRegexp:${PROJECT_BASE_URL}, {subdomain:[^.]+}.${PROJECT_BASE_URL}'

  pma:
    network_mode: traefik_network
    environment:
      # Our traefik needs the exact name instead just "mariadb" since
      # it holds many containters and each one has it own unique name.
      PMA_HOST: "${PROJECT_NAME}_$DB_HOST"

  mailhog:
    network_mode: traefik_network

  frontend:
    container_name: ${PROJECT_NAME}_frontend
    image: frontid/docker-front-tools:latest
    network_mode: traefik_network
    volumes:
      - ./:/var/www/html
    command: tail -f /dev/null
