version: "3"

services:

  traefik:
    container_name: proxy_traefik
    build: ./traefik
    network_mode: traefik_default
    restart: always
    command: -c /dev/null --web --docker --logLevel=INFO
    ports:
      - '80:80'
      - '443:443'
      - '8080:8080' # Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock