version: "2"

services:

  traefik:
    container_name: proxy_traefik
    build: ./traefik
    network_mode: traefik_network
    restart: always
    command: --web --docker --logLevel=DEBUG
    ports:
      - '8000:80'
      - '4430:443'
      - '8080:8080' # Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
