site_name: Dockerizer
repo_url: https://github.com/frontid/dockerizer
edit_uri: ""
nav:
    - Home: index.md
    - Install: install.md
    - Quickstart: quickstart.md
    - Domains: domains.md
    - dk the dockerizer cli: dk.md
    - The .docker.env file: dockerenv.md
    - Available commands: commands.md
    - Requirements: requirements.md
    - Extra containers: extra-containers.md
    - Uninstall: uninstall.md
    - Troubleshoot: troubleshoot.md
    - Mac: mac.md
theme: readthedocs
