site_name: Dockerizer
pages:
    - Home: index.md
    - Install: install.md
    - Domains: domains.md
    - dk the dockerizer cli: dk.md
    - The .docker.env file: dockerenv.md
    - Available commands: commands.md
    - Requirements: requirements.md
    - Troubleshoot: troubleshoot.md
theme: readthedocs